### PR TITLE
Implement Arm64 Clock

### PR DESCRIPTION
**Pull request by zhangkehong2brad**
Implement Arm64 Clock

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by Orvid** [comment]
@zhangkehong2brad Any chance you could sign that CLA so that we can merge this?

**Comment by zhangkehong2brad** [comment]
@Orvid I have signed it.

**Comment by Orvid** [comment]
Yep, I can confirm that, the bot seems to have been grumpy at the time, but you are listed internally as having signed it. (I'd add the CLA signed label myself if I could)

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
