### PR TITLE
fix: add pkg-config install to Dockerfile

### PR DESCRIPTION
**Pull request by asbubam**
add pkg-config install to Dockerfile
for https://github.com/facebook/mcrouter/issues/154

### CODE REVIEW

**Comment by sodabrew** [comment]
+1 this is necessary for a Docker build with the provided Dockerfile.

**Comment by sodabrew** [comment]
On further reflection, I suggest changing https://github.com/asbubam/mcrouter/blob/master/mcrouter/scripts/install_ubuntu_14.04.sh instead.

**Comment by asbubam** [comment]
@sodabrew If install_ubuntu_14_04.sh file needs 'pkg-config', all of install_ubuntu_xx_xx.sh files need to add 'pkg-config'. right?

**Comment by asbubam** [comment]
@andreazevedo Could you check this PR if you can?

**Comment by sodabrew** [comment]
@asbubam That's probably true for the other Ubuntus, but I haven't tested personally.

**Comment by jmswen** [comment]
@asbubam Thank you for fixing this.  Should be pulled shortly.

**Pull request closed without merging**
