### PR TITLE
Update Dockerfile to Ubuntu Xenial

### PR DESCRIPTION
**Pull request by erikwebb**
Also relocate Dockerfile to remove the need to checkout source from
GitHub at build time.

### CODE REVIEW

**Comment by erikwebb** [comment]
Alarmingly, this creates a 2.53GB Docker image! I'll also play around with building on Alpine.

**Comment by erikwebb** [comment]
@orishu I'm happy to work either way. Unfortunately, it's not clear if both are needed as they both seem to be used for testing and installation. One primary issue though is that both of the current Dockerfile implementations checkout this repo via git rather than using the local checkout. This makes testing very difficult.

**Comment by Lord-Y** [comment]
@erikwebb here is my Dockerfile:
`FROM            ubuntu:16.04

MAINTAINER      Lord-Y <yohann@lord-y.com>

ENV             MCROUTER_VERSION         0.39.0-1
ENV             DEBIAN_FRONTEND         noninteractive

RUN             apt-get update && apt-get install -y git sudo build-essential software-properties-common wget dirmngr apt-transport-https && \
		wget -O - https://facebook.github.io/mcrouter/debian/PUBLIC.KEY | sudo apt-key add && \
		echo 'deb https://facebook.github.io/mcrouter/debian xenial contrib' > /etc/apt/sources.list.d/mcrouter.list && \
		apt-get update && apt install -y mcrouter=$MCROUTER_VERSION
ENV             DEBIAN_FRONTEND newt`

Everything works perfectly and my docker image is only 490MB which is okay for me :)
The binary is located at /usr/bin/mcrouter.

**Comment by erikwebb** [comment]
I'm going to close this and re-focus my effort on using Alpine. I don't think an Ubuntu-based image is what fits my project atm.

**Pull request closed without merging**
