### PR TITLE
Some attempts of OS X compilation

### PR DESCRIPTION
**Pull request by 191919**
The original post is in https://github.com/facebook/hhvm/issues/5344.

Note that this is far away from a working copy of mcrouter under OS X. It just tries to make mcrouter compilable under OS X. Some functionalities are disabled because of lacks of Linux-specific syscalls.

### CODE REVIEW

**Comment by alikhtarov** [comment]
@191919 Please see the result of the Travis CI build - some of your changes don't compile

**Comment by 191919** [comment]
I reversed the commit `a6e5993`.

**Comment by andreazevedo** [comment]
Hey @191919,

Sorry about the huge delay from our side. :(
I was looking at your code today and looks like it needs to be rebased, do you mid rebasing? If you don't want to work on that anymore, that's also fine, I can work on that for you.

Thank you very much,
Andre

**Comment by andreazevedo** [comment]
Hello @191919,
I'm closing this PR, but feel free to rebase and reopen if still need it.
Thank you!

**Pull request closed without merging**
